version: 0.2

env:
  parameter-store:
    github_ssh_key: "github_ssh_key"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
      - echo "deb https://dl.bintray.com/loadimpact/deb stable main" | sudo tee -a /etc/apt/sources.list
      - apt-get update
      - apt-get install k6

  build:
    commands:
      - k6 run start.js --http-debug=full
